### PR TITLE
Gameplay fixes

### LINKED ISSUE #455: Text Holograms are not present after a rejoin
### Make sure to check before creating a Bug Report

- [x] The issue isn't already found on the Issue tracker.
- [x] My issue is about **BedWars2023** and not any addon.
- [x] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

When you rejoin a game the holograms (gens, npcs, ...) aren't there anymore

### Expected Behaviour

The holograms should perform as normal after a rejoin

### How to Reproduce

1. Launch a bw2023 game
2. /leave 
3. /bw rejoin
4. holograms aren't there anymore

### Console Log

_No response_

### Errors

_No response_

### Additional Info

Paper asp 1.21.8 bw2023 Mr ceasar fix for shop lore

Its probably after the massive refactor of holograms from kiiya that this happens

### PR DESCRIPTION
**Pull request by KKiiya**
- Fixed Holograms becoming invisible after a player has rejoined the game
- Fixed items being droppeable/storeable in the player inventory or cursor, making it impossible for the player to move the inventory items while falling. (This maybe should change slightly and check for every inventory click whether the player has blocks under)

### CODE REVIEW

**Comment by OXipro** [comment]
ggs

File: bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java [hunk 1]
```diff
@@ -993,6 +992,12 @@ public void removePlayer(@NotNull Player p, boolean disconnect, boolean skipPart
         List<ShopHolo> holos = shopHolosIso.getOrDefault(iso, Collections.emptyList());
         for (ShopHolo holo : holos) holo.clearForPlayer(p);
 
+        for (IGenerator o : getOreGenerators()) {
+            HashMap<String, IGenHolo> genHolos = o.getLanguageHolograms();
+            IGenHolo holo = genHolos.get(iso);
+            if (holo != null) holo.removePlayer(p);
+        }
+
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java:1000]: shouldnt this be done by the holo.clearforplayer? Maybe that function is broken and should then be fixed instead

**Review by tomkeuper — COMMENTED** [review]
Only one commend, the rest looks good to me!

File: bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java (hunk 1 above)
Comment (tomkeuper) [reply bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java:1000]: GenHolo != Shop holo

**Review by tomkeuper — APPROVED** [review]
