### PR TITLE
Gameplay and Visual bugs fixes + Performance Improvements

### LINKED ISSUE #427: Loading terrain... when player die
### Make sure to check before creating a Bug Report

- [x] The issue isn't already found on the Issue tracker.
- [x] My issue is about **BedWars2023** and not any addon.
- [x] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Gameplay Bug

### What happened?

When a player dies during a match, the screen shows “Loading terrain...”, which usually happens when a player is teleported between worlds.

So it seems like after dying, the player is being teleported to another world and then back to the game world.

https://github.com/user-attachments/assets/92a8c53f-df4f-4d55-9605-b1646360a654

### Expected Behaviour

The “Loading Terrain” screen should not appear when a player dies. The player should instantly respawn in spectator mode directly in the same game world without being teleported between worlds.

### How to Reproduce

Just die by a player or void

### Console Log

No Error

### Errors

No Error

### Additional Info

N/A

### PR DESCRIPTION
**Pull request by KKiiya**
## Fixes
- Fix player seeing loading world screen
- Fix HologramTask not updating, leading into invisible holograms for older versions
- Fix ShopHolo instances creating multiple times per player
- Fix ShopHolo instances not being saved in Arena class
- Fix hologram update logic for BedWarsTeam#respawnMember
- Fix double death message
- Fix generator holograms not updating properly
- Fix loading world screen after ingame death
- Fix TNT damage logic
- Fix TNT propell logic
- Fix Fireball damage logic
- Fix Void infinitely Tracking kill after LastHit
- Fix Kill logic giving kill to previous LastHit instead of most recent LastHit
- Fix UnhandledException on HologramTask after player disconnected
- Fix pregame items being movable
-----
## Improvements
- Add multiple checks to prevent double PlayerDeathEvent calls
- Add VersionSupport#callPlayerDeathEvent to call event across multiple versions
- Add method to display fake damage with VersionSupport
- Make OneTick task run Asynchronously
- Prevent hologram from updating for a player that is not inside it
-----
## Misc
- Replace BedHolo instances for IBedHolo
- Remove IArena argument from ShopHolo constructor
- Replace List<Player> calls for Iterator<Player> to increase compatibility
- Replace List<Player> for Set<Player> in BedWarsTeam.java to prevent repeated players

### CODE REVIEW

**Review by tomkeuper — APPROVED** [review]

**Review by Lagggpixel — APPROVED** [review]

**Comment by tomkeuper** [comment]
btw maybe we have to manually fire a death event so the listeners work properly?

**Comment by KKiiya** [comment]
That is, in fact, a great idea. I don't know how I didn't think about that. Soon changes will be applied.

File: bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/team/BedWarsTeam.java [hunk 1]
```diff
@@ -467,6 +470,9 @@ public void respawnMember(@NotNull Player p) {
         }
         Bukkit.getPluginManager().callEvent(new PlayerReSpawnEvent(p, getArena(), this));
         nms.sendPlayerSpawnPackets(p, getArena());
+        for (Player aPlayer : arena.getWorld().getPlayers()) {
+            BedWars.nms.spigotShowPlayer(p, aPlayer);
+        }
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/team/BedWarsTeam.java:475]: I assume this is a possible fix for the possible invis issues?

File: bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java [hunk 2]
```diff
@@ -2874,16 +2900,17 @@ private void sendToMainLobby(Player player) {
...
                 plugin.getLogger().log(Level.SEVERE, player.getName() + " was teleported to the main world because lobby location is not set!");
-            } else {
-                PaperSupport.teleportC(player, config.getConfigLoc("lobbyLoc"), PlayerTeleportEvent.TeleportCause.PLUGIN);
-            }
+            } else PaperSupport.teleportC(player, config.getConfigLoc("lobbyLoc"), PlayerTeleportEvent.TeleportCause.PLUGIN);
+        }
+        World w = player.getWorld();
+        for (Player p : w.getPlayers()) {
+            BedWars.nms.spigotShowPlayer(player, p);
+            BedWars.nms.spigotShowPlayer(p, player);
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/tomkeuper/bedwars/arena/Arena.java:2913]: Same as this?

**Review by tomkeuper — APPROVED** [review]

**Review by tomkeuper — APPROVED** [review]
