### PR TITLE
Some tiny updates to the api (IArena.java), spanish lang rework and min Y build added to the arena config

### LINKED ISSUE #59: message for build limit reached
**Describe the bug**
When building to the build limit set in the config there is no message displaying that you've reached the build limit.
This might be a feature but I concider this a bug for now

**To Reproduce**
build to the build limit

**Expected behavior**
A message in chat that the build limit has been reached

### PR DESCRIPTION
**Pull request by KKiiya**
Added generator api endpoints
added min/max build height messages

### CODE REVIEW

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/commands/bedwars/subcmds/sensitive/setup/SetMinBuildHeight.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+        }
+        return true;
+    }
+
+    /**
+     * Manage sub-command tab complete
+     */
+    @Override
+    public List<String> getTabComplete() {
+        return Arrays.asList("180", "256");
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/commands/bedwars/subcmds/sensitive/setup/SetMinBuildHeight.java]: Could you make this either null or normal values for the min height.

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java [hunk 2]
```diff
@@ -161,6 +161,10 @@ public void onBlockPlace(BlockPlaceEvent e) {
                 e.setCancelled(true);
                 return;
             }
+            if (e.getBlockPlaced().getLocation().getBlockY() <= a.getConfig().getInt(ConfigPath.ARENA_CONFIGURATION_MIN_BUILD_Y)) {
+                e.setCancelled(true);
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java:166]: Would you also like to send a message that the min height has been reached? :)

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java [hunk 3]
```diff
@@ -2511,6 +2511,16 @@ public Location getSpectatorLocation() {
         return spectatorLocation;
     }
 
+    @Override
+    public void setAllowMapBreak(boolean value) {
+        getConfig().set(ConfigPath.ARENA_ALLOW_MAP_BREAK, value);
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java:2516]: Im not sure if setting this vallue will also make it take affect immediately

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java [hunk 4]
```diff
@@ -320,7 +319,7 @@ public void onEnable() {
                 //registerEvents(new ArenaListeners());
                 ArenaSocket.lobbies.addAll(config.getList(ConfigPath.GENERAL_CONFIGURATION_BUNGEE_OPTION_LOBBY_SERVERS));
                 new SendTask();
-                registerEvents(new AutoscaleListener(), new PrePartyListener(), new JoinListenerBungee());
+                registerEvents(new AutoscaleListener(), new JoinListenerBungee());
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java:332]: Whats the reason of removing the PrePartListener?

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java (hunk 3 above)
Comment (KKiiya) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java:2516]: Yes this will take effect inmediately, ive tested it with an addon

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java (hunk 4 above)
Comment (KKiiya) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java:332]: It didnt do anything, its just called it for nothing and it was deprecated with only 2 usages (when listening to it)

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/commands/bedwars/subcmds/sensitive/setup/SetMinBuildHeight.java (hunk 1 above)
Comment (KKiiya) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/commands/bedwars/subcmds/sensitive/setup/SetMinBuildHeight.java]: Yes, didnt notice that, sorry

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java (hunk 2 above)
Comment (KKiiya) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java:166]: Done (sorry for the delayed response)

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java [hunk 5]
```diff
@@ -378,6 +377,7 @@ public ItemStack getOre() {
 
     @Override
     public void disable() {
+        arena.getOreGenerators().remove(this);
```
Comment (tomkeuper) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java:380]: I assume this is to fix the api issue, did you test if it works?

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java (hunk 4 above)
Comment (tomkeuper) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java:332]: I see it was marked for removal aswell

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java (hunk 5 above)
Comment (tomkeuper) [reply bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java:380]: I'll assume it works for now, otherwise we will take a look at it with the api fixes

**Review by tomkeuper — APPROVED** [review]
